version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: beerpong
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: beerpong
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: beerpong@web.de
      PGADMIN_DEFAULT_PASSWORD: beerpong

  bpbackend:
    image: gladom95/beeerpong-backend
    container_name: bpbackend
    ports:
      - "8082:8082"
    volumes:
      - ./go/cmd/config.json:/app/beerpong-server/

