version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: beerpong
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: beerpong
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: beerpong@web.de
      PGADMIN_DEFAULT_PASSWORD: beerpong

