export const DemoTeams: string[] = [
    "Flying Eagles",
    "Pupskanone Jessica",
    "Volltrottel",
    "Freispiel",
    "Dummkoepfe",
    "Tulpe",
    "Mine",
    "Hagge",
    "Hubbe",
    "Aaron",
    "Raphi",
    "Anna",
    "Patrick",
    "Philli",
    "Spleiss",
    "Kaeddey",
    "Anneika",
    "Kareina",
    "Luki",
    "Benno",
    "Stefge",
    "Kevin",
    "Manolo",
    "Julsi",
    "LovePaddy",
    "Gerd",
    "Myrtha",
    "Silvi",
    "Frido",
    "Selina"
]